// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/meroedu/meroedu/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// AttachmentRepository is an autogenerated mock type for the AttachmentRepository type
type AttachmentRepository struct {
	mock.Mock
}

// CreateAttachment provides a mock function with given fields: ctx, attachment
func (_m *AttachmentRepository) CreateAttachment(ctx context.Context, attachment domain.Attachment) error {
	ret := _m.Called(ctx, attachment)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Attachment) error); ok {
		r0 = rf(ctx, attachment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
