// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/meroedu/meroedu/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// AttachmentUserCase is an autogenerated mock type for the AttachmentUserCase type
type AttachmentUserCase struct {
	mock.Mock
}

// CreateAttachment provides a mock function with given fields: ctx, attachment
func (_m *AttachmentUserCase) CreateAttachment(ctx context.Context, attachment domain.Attachment) (*domain.Attachment, error) {
	ret := _m.Called(ctx, attachment)

	var r0 *domain.Attachment
	if rf, ok := ret.Get(0).(func(context.Context, domain.Attachment) *domain.Attachment); ok {
		r0 = rf(ctx, attachment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Attachment)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, domain.Attachment) error); ok {
		r1 = rf(ctx, attachment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
