// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/meroedu/meroedu/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// CategoryRepository is an autogenerated mock type for the CategoryRepository type
type CategoryRepository struct {
	mock.Mock
}

// CreateCategory provides a mock function with given fields: ctx, Category
func (_m *CategoryRepository) CreateCategory(ctx context.Context, Category *domain.Category) error {
	ret := _m.Called(ctx, Category)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Category) error); ok {
		r0 = rf(ctx, Category)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteCategory provides a mock function with given fields: ctx, id
func (_m *CategoryRepository) DeleteCategory(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx, start, limit
func (_m *CategoryRepository) GetAll(ctx context.Context, start int, limit int) ([]domain.Category, error) {
	ret := _m.Called(ctx, start, limit)

	var r0 []domain.Category
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []domain.Category); ok {
		r0 = rf(ctx, start, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Category)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, start, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *CategoryRepository) GetByID(ctx context.Context, id int64) (domain.Category, error) {
	ret := _m.Called(ctx, id)

	var r0 domain.Category
	if rf, ok := ret.Get(0).(func(context.Context, int64) domain.Category); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Category)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCategory provides a mock function with given fields: ctx, Category
func (_m *CategoryRepository) UpdateCategory(ctx context.Context, Category *domain.Category) error {
	ret := _m.Called(ctx, Category)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Category) error); ok {
		r0 = rf(ctx, Category)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
