// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/meroedu/meroedu/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// ContentStorage is an autogenerated mock type for the ContentStorage type
type ContentStorage struct {
	mock.Mock
}

// CreateContent provides a mock function with given fields: ctx, content
func (_m *ContentStorage) CreateContent(ctx context.Context, content domain.Content) error {
	ret := _m.Called(ctx, content)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Content) error); ok {
		r0 = rf(ctx, content)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DownloadContent provides a mock function with given fields: ctx, fileName
func (_m *ContentStorage) DownloadContent(ctx context.Context, fileName string) (string, error) {
	ret := _m.Called(ctx, fileName)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, fileName)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, fileName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
