FROM golang:1.14.2-alpine3.11

RUN apk update && apk upgrade && \
    apk --update add git make

WORKDIR /app
COPY go.mod . 
COPY go.sum .
RUN go mod download
RUN go get -u github.com/cosmtrek/air

COPY . .

ENTRYPOINT air .air.conf
